### ISSUE TITLE
Meridian Interviews: Talk to potential users of framework

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#24]
Meridian interviews are for 3 reasons:
1. Talk to [Station Module Builders Pipeline & PMF](https://docs.google.com/spreadsheets/d/1BOCSzAWXcN09JD31kW6NeAJNLT77J1y_Db2crC9HCzI/edit?usp=sharing) to validate demand for Meridian _beyond SPARK_
2. Talk to potential users to inform the process of ensuring that the Meridian Framework is generalizeable
3. Validate how potential users / devs interact with Meridian primitives through interviews

**Comment by juliangruber** [comment]
Do we have results for this somewhere?
