### ISSUE TITLE
Spark Interviews: Talk to potential Spark users

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#25]
Spark interviews are for 2 reasons:
1. The components of Spark (specifically proof of data possession & retrieval attestation) have relevance _beyond the first use case_, which is Spark module running inside of Station
2. The Spark module (once sufficiently running on Station) produces data that is highly relevant to many aspects of the Filecoin ecosystem (e.g. Reputation WG), which may even be sources of revenue

**Comment by coreymjames** [comment]
Potential Beneficiaries of SPARK data
- Storage providers
- Retrieval incentives
- Fil+
- Network Growth

**Comment by juliangruber** [comment]
Hey @coreymjames, could you please share the results of these interviews somewhere?

**Comment by coreymjames** [comment]
They're within Matt's Google Drive. Will request that he organize into a
folder for easier sharing.

*Corey James*
+1.504.383.3338
LinkedIn <https://www.linkedin.com/in/coreymjames/>
