### ISSUE TITLE
Station Interviews: Talk to potential Module Builders

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#26]

**Comment by MF416** [comment]
I don't think is completed?

**Comment by coreymjames** [comment]
It isn't, but we have duplicates and i am cleaning up the board.

**Comment by coreymjames** [comment]
Will remove other duplicate and use this one.

**Comment by coreymjames** [comment]
This has been dissected into more granular issues for individual interviews
