### ISSUE TITLE
Create SPARK business model doc (i.e. sustainable funding model)

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#28]
Work being performed here:
1. [Spark Business Model](https://www.notion.so/pl-strflt/Spark-Business-Model-93937387eed147c1b93cb2029c755571)
2. [Station Module 1 (SPARK) Modeling Spreadsheet](https://docs.google.com/spreadsheets/d/1nKYIYkKUC3o-oxXjGiCuXsOP9QEhsv8FFRpiCeBg6P4/edit#gid=0)

**Comment by MF416** [comment]
We should both be doing this one

**Comment by coreymjames** [comment]
Splitting this into sub-tasks and re-assigning to @patrickwoodhead
