### ISSUE TITLE
Legal: Align with Legal on Station/Meridian Topics (see description)

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#33]
If needed, create Meridian Legal Report

### Update:
Station/Meridian Legal topics now have three elements:
1. Upcoming station node payments (any roadblocks)
2. Storing IPv4 addresses (if compliant with GDPR, etc.)
3. Significance of block-reward like payounts for an onchain IE

These are being discussed [here](https://protocollabs.slack.com/archives/C061J6UUA1E/p1697111734969809)

**Comment by MF416** [comment]
Lets sync on this to scope it out

**Comment by coreymjames** [comment]
Station/Meridian Legal topics now have three elements:
1. Upcoming station node payments (any roadblocks)
2. Storing IPv4 addresses (if compliant with GDPR, etc.)
3. Significance of block-reward like payounts for an onchain IE


These are being discussed [here](https://protocollabs.slack.com/archives/C061J6UUA1E/p1697111734969809)

**Comment by geomatrick** [comment]
We need to create a terms of service doc to close this ticket. See the Saturn one here: https://tan-pantydraco-e40.notion.site/Saturn-Program-Information-2d820a4aacca4378ba503de30198b3c8

**Comment by juliangruber** [comment]
Wasn't Monica Ortel going to draft the ToS? https://protocollabs.slack.com/archives/C061J6UUA1E/p1697212744601309

**Comment by geomatrick** [comment]
I don't think she said she is going to do it, just that it is an AI for the group.

**Comment by coreymjames** [comment]
Draft ToS:
https://docs.google.com/document/d/18wj6WgRaOc-gX85RodEsMP1njIetPFbG6QYJFkOzpCM/edit
