### ISSUE TITLE
SPARK design doc and roadmap to LabWeek'23

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#37]

**Comment by bajtos** [comment]
The design doc and the roadmap milestones are described here: https://www.notion.so/pl-strflt/SPARK-roadmap-to-LabWeek-23-5d41e603859a4e32908d3c818e3d4542

@coreymjames What else is missing before we can close this task as done?

**Comment by coreymjames** [comment]
This can be marked as done.

A separate/similar issue will be created related to polishing a public-facing version, but this is done for now 👍🏽
