### ISSUE TITLE
Interview: SP Performance Test Requirements

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#40]

**Comment by juliangruber** [comment]
@coreymjames can you please share the results of this?

**Comment by MF416** [comment]
@juliangruber See this link: https://docs.google.com/document/d/133cxPMS5l4ATmAYOpTkqT9xPNpcFyAJAK0B3-5ss3vo/edit?usp=sharing

Also all interviews are in [THIS FOLDER](https://drive.google.com/drive/u/0/folders/1PkzsYsUQjBftqPlK3BvsT0MQ3S9YSQbS)
