### ISSUE TITLE
Create website overview doc for team alignment & Subvisual scoping

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#45]
Need to determine what aspects they are working on among the digital assets we need for LabWeek, which include:

Station:
- website updates
- desktop app updates?

Meridian
- website (if any)
- Meridian docs

Spark
- website (if any)
- docs

Station x Meridian design spec created by Julian:
https://www.notion.so/pl-strflt/Station-x-Meridian-design-spec-d2bbdc0c62cc4d939d2b467d1cbd6264

**Comment by juliangruber** [comment]
@coreymjames can you share the document please?

**Comment by coreymjames** [comment]
https://www.notion.so/LabWeek-Public-Website-Docs-Work-7c3c0540c45b493eb72f2cd8db3aabff

I see you already left comments in it, but this is the doc
