### ISSUE TITLE
Update Grafana dashboard with fraud metrics

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#47]

**Comment by juliangruber** [comment]
Assigned to @bajtos how is going to work on fraud and knows how to maintain the dashboards as well. Please reassign if you would like me to handle this instead

**Comment by bajtos** [comment]
I started a new SPARK dashboard here:
https://protocollabs.grafana.net/d/c4bd3c80-9360-4ea3-8b75-c5ecea90765b/spark?orgId=1

I'll be adding new visualisations incrementally.

**Comment by bajtos** [comment]
Closing as done. The first visualisations are live. I'll be adding more charts as part of the individual tasks improving our fraud detection.

**Comment by bajtos** [comment]
![Image](https://github.com/filecoin-station/proj-mgmt/assets/1140553/d834a659-f1fc-4371-96c9-1a186314ea6d)
