### ISSUE TITLE
Transition <dev> tasks from Notion Roadmap to GitHub Project

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#52]
Read through [Notion SMS Roadmap](https://www.notion.so/pl-strflt/Pre-LabWeek-S-M-S-Outcomes-Roadmap-2071e3f4a8b0402199588bf423a59f74#53efda9a46d74bf8970ef6f64b8ddc99) and [Notion SPARK Roadmap to LabWeek](https://www.notion.so/pl-strflt/SPARK-roadmap-to-LabWeek-23-5d41e603859a4e32908d3c818e3d4542) and ensure that `dev` issues / sub-tasks are 1) captured in GitHub Issues and 2) connected to their associated milestones

Note: This has been done for `PM` issues, but CJ is adding this here to ensure dev issues don't slip through the cracks during this transition.

**Comment by bajtos** [comment]
Created the following roadmap items:
- https://github.com/filecoin-station/roadmap/issues/41
- https://github.com/filecoin-station/spark/issues/30
- https://github.com/filecoin-station/roadmap/issues/43
- https://github.com/filecoin-station/proj-mgmt/issues/54

Over to you, @juliangruber

**Comment by juliangruber** [comment]
@bajtos I believe these issues are still missing the assignments to their respective milestones

**Comment by juliangruber** [comment]
@coreymjames where do you think milestones should be created? Or are you thinking about milestone-type issues in the roadmap repo?

**Comment by juliangruber** [comment]
I created issues for my work

**Comment by coreymjames** [comment]
@juliangruber we made milestones within GH that align with the roadmap (see [this](https://github.com/orgs/filecoin-station/projects/1/views/14) proj board view). They all exist within the proj-mgmt repo, but i also created _identically named_ milestones within the spark repo's [milestones](https://github.com/filecoin-station/spark/milestones) for M3 & M4.

This duplicated milestones solution is not ideal. It's a byproduct of limited functionality within GitHub, in that issues in two separate repos cannot be added within one shared milestone. In other words, milestones are particular to repo's and not to GitHub organizations.

Does this make sense?

If this solution works well enough, I can create milestones within Meridian and other necessary repo's so that we have accurate labelling of issues and their associated milestones.

**Comment by coreymjames** [comment]
Going to close this issue, but we can continue the Milestones discussion in the slack thread i created.

**Comment by juliangruber** [comment]
Reopening as my issues aren't assigned to milestones yet 👋

**Comment by juliangruber** [comment]
@coreymjames ok, would be great if you could duplicate these milestones also into the meridian-ie repo 🙏

**Comment by coreymjames** [comment]
done
