### ISSUE TITLE
Website: Meet with Subvisual

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#69]

**Comment by juliangruber** [comment]
@coreymjames do we have meeting notes for this?

**Comment by coreymjames** [comment]
There's no notes, as this meeting was brief and was primarily to share
access (with me) to the Webflow Station site.

PW and I agreed that, because our other website and branding related needs
were less intensive (i.e. will primarily be created using Notion/Super), a
contract with Subvisual was likely overkill.

Consequently, I met with a designer that was formerly part of
Cycle/Crcle to discuss branding assets (notes here
<https://docs.google.com/document/d/1Kxr0jijx7Z5RCNHNkD1IbrZ5UWT4kQOm6YtDllCv4VY/edit>),
and Patrick and I are working on first drafts of the Spark and Meridian
sites (for which we are hoping for Julian/Miro input once it is more
complete).

**Comment by juliangruber** [comment]
Thank you!
