### ISSUE TITLE
Draft user stories for S/S/M

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#9]

**Comment by MF416** [comment]
Add perspective on:

- [ ] FIL+ notaries
- [ ] SP's

**Comment by coreymjames** [comment]
See [here](https://www.notion.so/pl-strflt/User-Story-Mapping-275373d942b648f488e99705ac446b50)

This doc is still technically WIP, but setting it as done for now until a need arises to revisit it and refine it further. 

TLDR: I short-changed the "Meridian PaaS" user story, as that needs a thorough treatment and would only be able to be pursued post-labweek.
