### ISSUE TITLE
Station/Meridian Product Thesis Doc

### ISSUE THREAD

**Issue by coreymjames** [CheckerNetwork/proj-mgmt#95]
https://docs.google.com/document/d/1E45vQ1PL4xnBNk8ECb69_q_bcPZOOxbOny3BxInGOVA/edit

**Comment by coreymjames** [comment]
@patrickwoodhead I started working on this, but it overlaps with elements from the [GTM doc](https://docs.google.com/presentation/d/1XXjh4x77MqJ9E5bI7Vfrnp7r8g5LeYYMcdlmvmRzpWQ/edit#slide=id.g2899eca51ac_0_186)

**Comment by geomatrick** [comment]
@coreymjames I think what would be useful in this doc is the market comparison. We should analyse other desktop network as well as Fleek, Koii, Titan and to some extent Saturn to see where there are similarities and differences and to understand what markets they are going after. we should also analyse how they intend to get value flows into their networks and whether Meridian could help them.
